# -*- coding: utf-8 -*-
"""Fibonacchi / Hashtable

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1IMci5Mfff0CxS6sayh1ihWdpxkWy2RnP
"""

def fibAdel(n: int) -> int:
  if n == 0: return n
  penultimo: int = 0
  ultimo:    int = 1
  for _ in range(1, n):
    penultimo, ultimo = ultimo, penultimo + ultimo
  return ultimo

if __name__ == "__main__":
  n = int(input("¿De qué posición quieres el valor de Fibonacci?: "))
  print(f"El {n}-ésimo valor de Fibonacci es: {fibAdel(n)}")

from typing import Generator

def fibGen(n: int) -> Generator[int, None, None]:
  yield 0
  if n > 0:
    yield 1
  penultimo: int = 0
  ultimo: int = 1
  for _ in range(1, n):
    penultimo, ultimo = ultimo, penultimo + ultimo
    yield ultimo

if __name__ == "__main__":
  n = int(input("¿Fibonacci hasta la posición?: "))
  for i in fibGen(n):
    print(i)

def fibAdel(n: int) -> int:
  """Calcula el n-ésimo número de Fibonacci de forma iterativa."""
  if n < 0:
    raise ValueError("n debe ser un número entero no negativo.")
  if n == 0:
    return 0
  if n == 1:
    return 1

  penultimo, ultimo = 0,1
  for _ in range(2, n + 1):
      penultimo, ultimo = ultimo, penultimo + ultimo
  return ultimo

if __name__ == "__main__":
  try:
    n = int(input("¿De qué posición quieres el valor de Fibonacci?: "))
    print(f"El {n}-ésimo valor de Fibonacci es: {fibAdel(n)}")
  except ValueError as e:
    print(f"Error: {e}")

"""Mejoras:
Validación de entrada:
Se verifica que n sea no negativo, evitando resultados incorrectos o errores.
Casos base explícitos:
Se manejan n = 0 y n = 1 directamente para mayor claridad y evitar cálculos innecesarios.
Manejo de excepciones;
Se utiliza un try-except al leer la entrada para capturar errores
Ahora el rango empieza en 2 hasta n+1

from typing import Generator

def fibGen(n: int) -> Generator[int, None, None]:
    """Genera los números de Fibonacci desde 0 hasta la posición n (inclusive)."""
    if n < 0:
        raise ValueError("n debe ser un número entero no negativo.")

    penultimo, ultimo = 0, 1
    yield penultimo  # F(0)
    if n == 0:
        return

    yield ultimo  # F(1)
    for _ in range(2, n + 1):
        penultimo, ultimo = ultimo, penultimo + ultimo
        yield ultimo


if __name__ == "__main__":
    try:
        n = int(input("¿Fibonacci hasta la posición?: "))
        print(f"Serie de Fibonacci hasta F({n}):")
        print(" ".join(str(num) for num in fibGen(n)))
    except ValueError as e:
        print(f"Error: {e}")


"""Mejoras:
Validación de entrada:
Se verifica que n no sea negativo para evitar resultados incorrectos o errores.
Manejo de excepciones:
Se capturan errores al leer la entrada del usuario.
Salida:
Los valores se muestran en una sola línea, separados por espacios

Los yield de 0 y 1 se hacen antes del bucle. El bucle comienza en 2, donde empieza la recurrencia.